qian/qian/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'base.views.home', name='home'),
    
    url(r"^users/", include("users.urls")),
    url(r'^stocks/', include('stocks.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

qian/stocks/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('stocks.views',
    url(r'^$', 'home', name='home'),
    url(r"^categories/$", "categories"),
)

qian/users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns("",
    url(r'^login/$', "django.contrib.auth.views.login", {"template_name": "users/login.html"}),
    url(r"^logout/$", "django.contrib.auth.views.logout_then_login"),
)

qian/stocks/models.py
from django.db import models

from uom.models import UOM

class Category(models.Model):
    code = models.CharField(max_length=6, unique=True)
    description = models.CharField(max_length=20, blank=True, unique=True)
    type = models.CharField(max_length=1, choices=[
            ("F", "Finished Goods"),
            ("M", "Raw Materials"),
            ("D", "Dummy Item - (No Movements)"),
            ("L", "Labor")
        ])
    
    class Meta:
        verbose_name_plural = "categories"
    
    def __unicode__(self):
        return self.code

class Stock(models.Model):
    code = models.CharField(max_length=20, unique=True)
    category = models.ForeignKey(Category)
    description = models.TextField(blank=True)
    barcode = models.CharField(max_length=50, unique=True)
    uom = models.ForeignKey(UOM, verbose_name="unit of measure")
    discontinued = models.BooleanField()
    
    def __unicode__(self):
        return self.code

qian/uom/models.py
from django.db import models

class UOM(models.Model):
    name = models.CharField(max_length=20)
    
    class Meta:
        verbose_name = "Unit of Measure"
        verbose_name_plural = "Units of Measure"
    
    def __unicode__(self):
        return self.name

qian/users/models.py
from django.db import models

# Create your models here.

qian/base/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

qian/stocks/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from models import Category

@login_required
def home(request):
    return render(request, "stocks/home.html")

@login_required
def categories(request):
    categories = Category.objects.all()
    return render(request, "stocks/categories/home.html", {
            "categories": categories,
        })

qian/uom/views.py
# Create your views here.

qian/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib import messages

def user_login(request):
    return render(request, "users/login.html")

def user_authenticate(request):
    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return redirect("/stocks/")
        else:
            messages.error(request, "Account has been disactivated.")
            return redirect("/users/login/")
    else:
        messages.error(request, "Invalid username or password")
        return redirect("/users/login/")

qian/base/templates/base.html
<!DOCTYPE html>

{% load bootstrap_toolkit %}
{% load url from future %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block base_title %}Qian{%endblock %} | Qian</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Johan Sim Jian An">
    {% bootstrap_stylesheet_tag %}
    <style type="text/css">
      body {
        padding-top: 60px;
      }
    </style>
    {% bootstrap_stylesheet_tag "responsive" %}
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    {% block base_extra_head %}{% endblock %}
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <a class="brand" href="/">Qian</a>
          
          <div class="nav-collapse collapse">
            <ul class="nav">
              {% block base_nav %}
                {% if user.is_authenticated %}
                  <li><a href="/stocks/">Stocks</a></li>
                {% endif %}
              {% endblock %}
            </ul>
            <ul class="nav pull-right">
              {% if user.is_authenticated %}
                <li><a href="/users/logout/">Logout</a></li>
              {% else %}
                <li><a href="/users/login/">Login</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      {% bootstrap_messages %}
      
      {% block base_content %}Empty page{% endblock %}
      
      <hr />
      
      <footer>
        <p>&copy; 2013 Johan Sim Jian An</p>
      </footer>
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    {% bootstrap_javascript_tag %}
  </body>
</html>

qian/base/templates/home.html
{% extends "base.html" %}

{% block base_content %}
  <div class="row">
    <div class="span6 offset3">
      <div class="hero-unit">
        <h1>Hello!</h1>
        <p>For authorized personnel only!</p>
        <p>
          <a class="btn btn-primary btn-large" href="/users/login/">Login</a>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

qian/stocks/templates/stocks/base.html
{% extends "base.html" %}

{% block base_title %}Stocks{% endblock %}

{% block base_content %}
  <div class="row">
    <div class="span3">
      <div class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
          <li class="nav-header">Categories</li>
          <li><a href="/stocks/categories/">List</a></li>
        </ul>
      </div>
    </div>
    
    <div class="span9">
      {% block stocks_content %}{% endblock %}
    </div>
  </div>
{% endblock %}

qian/stocks/templates/stocks/categories/home.html
{% extends "stocks/base.html" %}

{% block stocks_content %}
  <div class="row">
    <div class="span9">
      <h1>Categories</h1>
      <hr>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Code</th>
            <th>Description</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          {% for category in categories %}
            <tr>
              <td>{{ category.code }}</td>
              <td>{{ category.description }}</td>
              <td>{{ category.get_type_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

qian/stocks/templates/stocks/home.html
{% extends "stocks/base.html" %}

{% block stocks_content %}
  <div class="row">
    <div class="span12">
      <p>This is the STOCKS home.</p>
    </div>
  </div>
{% endblock %}

qian/users/templates/users/login.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block base_content %}
  <div class="row">
    <div class="span6 offset3">
      {% if form.errors %}
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          Your username and password didn't match. Please try again.
        </div>
      {% endif %}
      <h1>Login</h1>
      <form class="form-horizontal" action="{% url 'django.contrib.auth.views.login' %}" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Login</button>
            <input type="hidden" name="next" value={{ next }} />
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock %}